# Generated by Django 6.0.4 on 2026-05-04 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('facilities', '0001_initial'),
        ('passengers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('trip_type', models.CharField(choices=[('single', 'Single'), ('recurring', 'Recurring')], default='single', max_length=10)),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('approximate_dropoff_time', models.TimeField(blank=True, null=True)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('special_requirements', models.CharField(choices=[('standard', 'Standard'), ('stretcher', 'Stretcher'), ('oxygen', 'Oxygen'), ('wheelchair', 'Wheelchair')], default='standard', max_length=20)),
                ('estimated_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estimated_duration', models.PositiveIntegerField(default=0)),
                ('route_type', models.CharField(blank=True, max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('mileage_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('insurance', 'Insurance'), ('pay_later', 'Pay Later')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pay_later', 'Pay Later')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_route', 'In Route'), ('active', 'Active'), ('awaiting_signature', 'Awaiting Signature'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=25)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='facilities.facility')),
                ('parent_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='trips.trip')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='passengers.passenger')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['pickup_date', 'pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTripConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('days_of_week', models.JSONField(default=list)),
                ('end_date', models.DateField()),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_config', to='trips.trip')),
            ],
            options={
                'db_table': 'recurring_trip_configs',
            },
        ),
        migrations.CreateModel(
            name='TripPassengerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], default='other', max_length=10)),
                ('home_address', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_contacts', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_passenger_contacts',
            },
        ),
        migrations.CreateModel(
            name='TripSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_image', models.ImageField(upload_to='trips/signatures/')),
                ('signed_at', models.DateTimeField()),
                ('confirmed_by_driver', models.BooleanField(default=False)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_signatures',
            },
        ),
        migrations.CreateModel(
            name='TripStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_status_logs',
                'ordering': ['changed_at'],
            },
        ),
    ]
