# Generated by Django 6.0.4 on 2026-05-04 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('nursing_home', 'Nursing Home'), ('dialysis_center', 'Dialysis Center'), ('rehabilitation', 'Rehabilitation'), ('other', 'Other')], max_length=30)),
                ('facility_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('pickup_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_trips_this_month', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_revenue_this_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_last_date', models.DateField(blank=True, null=True)),
                ('avg_payment_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityBillingContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('insurance_no', models.CharField(blank=True, max_length=100)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_contact', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_billing_contacts',
            },
        ),
        migrations.CreateModel(
            name='FacilityContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('volume_commitment', models.PositiveIntegerField(default=0)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_contracts',
            },
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('w9_tax_form', 'W9 Tax Form'), ('hipaa_agreement', 'HIPAA Agreement'), ('insurance_certificate', 'Insurance Certificate'), ('contract', 'Contract'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='facilities/documents/')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_documents',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='FacilityPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_sedan_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('wheelchair_accessible_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stretcher_transport_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('wait_time_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('minimum_trips', models.PositiveIntegerField(default=0)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_pricing',
            },
        ),
        migrations.CreateModel(
            name='FacilityPrimaryContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_primary_contacts',
            },
        ),
        migrations.CreateModel(
            name='FacilityTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('w9_on_file', models.BooleanField(default=False)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_tax',
            },
        ),
    ]
