# Generated by Django 6.0.4 on 2026-05-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_provider_groups_provider_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='oxygen_base_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='oxygen_miles_included',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='oxygen_per_mile_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
