# Generated by Django 6.0.4 on 2026-05-09 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_type', models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle')], max_length=10)),
                ('holder_id', models.UUIDField()),
                ('holder_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('driver_license', 'Driver License'), ('insurance', 'Insurance'), ('cpr_certificate', 'CPR Certificate'), ('background_check', 'Background Check'), ('vehicle_registration', 'Vehicle Registration'), ('vehicle_insurance', 'Vehicle Insurance'), ('w9', 'W9'), ('hipaa_agreement', 'HIPAA Agreement'), ('others', 'Others')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file_reference', models.URLField(blank=True, max_length=500)),
                ('upload_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired')], default='valid', max_length=15)),
                ('days_until_expiration', models.IntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_documents',
                'ordering': ['days_until_expiration'],
            },
        ),
        migrations.CreateModel(
            name='PreTripInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('odometer', models.PositiveIntegerField()),
                ('fuel_level', models.CharField(choices=[('full', 'Full'), ('three_quarters', 'Three Quarters'), ('half', 'Half'), ('quarter', 'Quarter'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('all_clear', 'All Clear'), ('issues_found', 'Issues Found')], default='all_clear', max_length=15)),
                ('vehicle_exterior', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('vehicle_interior', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('tires', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('brakes', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('fluids', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('lights', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('safety_equipment', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('cleanliness', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('wheelchair_ramp', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=15)),
                ('dashboard_warning_lights', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=5)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('issue_photo', models.FileField(blank=True, null=True, upload_to='compliance/inspections/')),
                ('signature', models.FileField(upload_to='compliance/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='drivers.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'pre_trip_inspections',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('document_expiring', 'Document Expiring'), ('document_expired', 'Document Expired'), ('inspection_missed', 'Inspection Missed'), ('inspection_failed', 'Inspection Failed')], max_length=25)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('holder_type', models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle')], max_length=10)),
                ('holder_id', models.UUIDField()),
                ('holder_name', models.CharField(max_length=255)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='compliance.compliancedocument')),
                ('related_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='compliance.pretripinspection')),
            ],
            options={
                'db_table': 'compliance_alerts',
                'ordering': [models.Case(models.When(severity='critical', then=0), models.When(severity='warning', then=1), models.When(severity='info', then=2), default=3, output_field=models.IntegerField()), 'days_remaining'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_date', models.DateField()),
                ('inspection_submitted', models.BooleanField(default=False)),
                ('missed_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='drivers.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='vehicles.vehicle')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='compliance.pretripinspection')),
            ],
            options={
                'db_table': 'inspection_schedules',
                'ordering': ['-expected_date'],
                'unique_together': {('provider', 'driver', 'vehicle', 'expected_date')},
            },
        ),
    ]
