# Generated by Django 6.0.4 on 2026-04-30 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('vin_number', models.CharField(max_length=17, unique=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('wheelchair_accessible', 'Wheelchair Accessible'), ('stretcher', 'Stretcher')], max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('accessibility_features', models.CharField(choices=[('standard', 'Standard'), ('stretcher', 'Stretcher'), ('oxygen', 'Oxygen'), ('wheelchair', 'Wheelchair')], default='standard', max_length=20)),
                ('ramp_type', models.CharField(choices=[('fold_out', 'Fold Out'), ('roll_out', 'Roll Out'), ('none', 'None')], default='none', max_length=20)),
                ('securement_system', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('in_maintenance', 'In Maintenance'), ('on_trip', 'On Trip')], default='active', max_length=20)),
                ('registration_state', models.CharField(blank=True, max_length=50)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('inspector', models.CharField(blank=True, max_length=255)),
                ('assigned_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle_set', to='drivers.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'unique_together': {('provider', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='vehicles/documents/')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('monthly_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('liability_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('collision_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('comprehensive_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_insurance',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('mileage_at_service', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_mileage', models.PositiveIntegerField(default=0)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('upcoming_service', models.CharField(blank=True, max_length=255)),
                ('service_interval', models.PositiveIntegerField(default=0)),
                ('last_service_mileage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_maintenance',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
