# Generated by Django 6.0.4 on 2026-04-30 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_availability',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='DriverCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(choices=[('cpr', 'CPR'), ('first_aid', 'First Aid'), ('wheelchair_assistance', 'Wheelchair Assistance'), ('defensive_driving', 'Defensive Driving')], max_length=30)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_certifications',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('driver_license', 'Driver License'), ('insurance', 'Insurance'), ('cpr_certificate', 'CPR Certificate'), ('background_check', 'Background Check')], max_length=30)),
                ('file', models.FileField(upload_to='drivers/documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'driver_emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_state', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_licenses',
            },
        ),
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverWorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('trips_completed', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('worked', 'Worked'), ('off_day', 'Off Day')], default='off_day', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver_work_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='drivers/profiles/')),
                ('password', models.CharField(max_length=255)),
                ('status_employment', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('status_availability', models.CharField(choices=[('on_trip', 'On Trip'), ('available', 'Available'), ('break', 'Break'), ('off_duty', 'Off Duty')], default='off_duty', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
    ]
