# Generated by Django 6.0.4 on 2026-04-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_set', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='drivercertification',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driveremergencycontact',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverworklog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='drivers.driver'),
        ),
        migrations.AlterUniqueTogether(
            name='driveravailability',
            unique_together={('driver', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='drivercertification',
            unique_together={('driver', 'cert_type')},
        ),
        migrations.AlterUniqueTogether(
            name='driverworklog',
            unique_together={('driver', 'date')},
        ),
    ]
