# Generated by Django 6.0.4 on 2026-05-09 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssignmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drivers_considered', models.JSONField(default=list)),
                ('assignment_successful', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assignment_logs', to=settings.AUTH_USER_MODEL)),
                ('selected_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assignment_selections', to='drivers.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assignment_logs', to='trips.trip')),
            ],
            options={
                'db_table': 'ai_assignment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('completed_trips', models.PositiveIntegerField(default=0)),
                ('in_progress', models.PositiveIntegerField(default=0)),
                ('scheduled', models.PositiveIntegerField(default=0)),
                ('unassigned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_schedules',
                'ordering': ['-date'],
                'unique_together': {('provider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_method', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='drivers.driver')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.dailyschedule')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='trips.trip')),
            ],
            options={
                'db_table': 'schedule_slots',
                'ordering': ['trip__pickup_time'],
                'unique_together': {('schedule', 'trip')},
            },
        ),
    ]
