# Generated by Django 6.0.4 on 2026-05-09 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTripTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_route_to_pickup', 'En Route to Pickup'), ('passenger_onboard', 'Passenger Onboard'), ('arrived_at_dropoff', 'Arrived at Dropoff')], default='en_route_to_pickup', max_length=25)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_tracking', to='drivers.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_trip_tracking', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_tracking', to='trips.trip')),
            ],
            options={
                'db_table': 'active_trip_tracking',
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='drivers.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_locations',
            },
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='drivers.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_history', to='trips.trip')),
            ],
            options={
                'db_table': 'driver_location_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='driver_loca_driver__f8e3a5_idx'), models.Index(fields=['trip', 'timestamp'], name='driver_loca_trip_id_261f96_idx')],
            },
        ),
    ]
