# Generated by Django 6.0.4 on 2026-05-09 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header_data', models.JSONField(default=dict)),
                ('earnings_chart_data', models.JSONField(default=dict)),
                ('driver_status_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_cache',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('trip_volume', 'Trip Volume'), ('driver_hours', 'Driver Hours'), ('passenger_service', 'Passenger Service')], max_length=25)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_snapshots',
                'unique_together': {('provider', 'report_type', 'date_range_start', 'date_range_end')},
            },
        ),
    ]
