# Generated by Django 6.0.4 on 2026-05-04 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='passengers/profiles/')),
                ('preferred_language', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('mobility', models.CharField(choices=[('wheelchair', 'Wheelchair'), ('ambulatory', 'Ambulatory'), ('stretcher', 'Stretcher'), ('oxygen', 'Oxygen')], default='ambulatory', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('completed_trips', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passengers',
                'unique_together': {('provider', 'email'), ('provider', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='PassengerCommonLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_locations', to='passengers.passenger')),
            ],
            options={
                'db_table': 'passenger_common_locations',
                'ordering': ['-trips_count'],
            },
        ),
        migrations.CreateModel(
            name='PassengerEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], default='other', max_length=10)),
                ('home_address', models.TextField(blank=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='passengers.passenger')),
            ],
            options={
                'db_table': 'passenger_emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='PassengerInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('medicare_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medicaid_number', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='passengers.passenger')),
            ],
            options={
                'db_table': 'passenger_insurance',
            },
        ),
        migrations.CreateModel(
            name='PassengerMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('special_requirements', models.CharField(choices=[('standard', 'Standard'), ('stretcher', 'Stretcher'), ('oxygen', 'Oxygen'), ('wheelchair', 'Wheelchair')], default='standard', max_length=20)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('special_assistance_needs', models.TextField(blank=True, null=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='passengers.passenger')),
            ],
            options={
                'db_table': 'passenger_medical',
            },
        ),
        migrations.CreateModel(
            name='PassengerFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_associations', to='facilities.facility')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_associations', to='passengers.passenger')),
            ],
            options={
                'db_table': 'passenger_facilities',
                'unique_together': {('passenger', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='PreferredDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by_passengers', to='drivers.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_drivers', to='passengers.passenger')),
            ],
            options={
                'db_table': 'preferred_drivers',
                'ordering': ['-trips_count'],
                'unique_together': {('passenger', 'driver')},
            },
        ),
    ]
