# Generated by Django 6.0.4 on 2026-05-09 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('trip', 'Trip'), ('driver', 'Driver'), ('payment', 'Payment'), ('announcement', 'Announcement'), ('compliance', 'Compliance')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('provider', 'Provider'), ('driver', 'Driver')], max_length=10)),
                ('recipient_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('trip', 'Trip'), ('driver', 'Driver'), ('payment', 'Payment'), ('announcement', 'Announcement'), ('compliance', 'Compliance')], max_length=20)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_651bd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('provider', 'Provider'), ('driver', 'Driver')], max_length=10)),
                ('recipient_id', models.UUIDField()),
                ('trip_updates', models.BooleanField(default=True)),
                ('driver_alerts', models.BooleanField(default=True)),
                ('passenger_messages', models.BooleanField(default=True)),
                ('financial_alerts', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'unique_together': {('recipient_type', 'recipient_id')},
            },
        ),
    ]
